Fix #1212 : allow multiple events at the same moment
afup/web pull request #1223
Opened 2022-11-04 23:51 UTC by vinceAmstoutz

Solves #1212 

Current result for multiple events (2 or more): 

![desktop](https://user-images.githubusercontent.com/46444652/200090493-94c303d1-fadc-4ea3-be37-14bded117b37.png)

2022-11-05 14:10 UTC, vinceAmstoutz commented
@agallou Il faudra décider quoi faire pour les appels à la [méthode `getNextEvent` ](https://github.com/vinceAmstoutz/afup-web/blob/02ef59984a8d4793482f327b4dde8ea9aaca2a05/sources/AppBundle/Event/Model/Repository/EventRepository.php#L29) si on veut la supprimer car les autres dépendances ne gèrent actuellement un Event au lieu d'une collection.

2022-11-05 21:21 UTC, stakovicz requested changes

2022-11-05 21:21 UTC, stakovicz commented on sources/AppBundle/Event/Model/Repository/EventRepository.php
> +    }
Pourquoi avoir ajouté cette fonction ?
Est-ce que `getNextEvents()` ne pouvait pas faire l'affaire ?

2022-11-05 21:21 UTC, stakovicz commented on app/Resources/views/event/menu.html.twig
> +                <a class="navbar-brand hidden-xs" href="/event">{{ 'Évènements'|trans }}</a>
Je ne suis pas sûr que la modification soit nécessaire ici. Je pense que cela sort du cadre du ticket. 

C'est à confirmer avec @agallou

2022-11-05 21:21 UTC, stakovicz commented on app/Resources/views/event/switch.html.twig
> +                        <svg width="32" height="32"><use xlink:href="#octocat"></use></svg>
J'ai l'impression que ce SVG ne fonctionne pas, si ?

2022-11-06 10:13 UTC, vinceAmstoutz commented on app/Resources/views/event/menu.html.twig
> +                <a class="navbar-brand hidden-xs" href="/event">{{ 'Évènements'|trans }}</a>
Le problème c'est que le menu qui est inclus à ce niveau attend 1 objet `Event` et là on a une collection d'Event pour afficher les boutons qui redirigent vers les différents évènements. 
Donc à mon avis 
- soit on change le format en entrée 
- soit il faut enlever le menu ou le surcharger si on ne veut pas utiliser cette méthode qui rajoute un use case dans le `menu.html.twig`.

2022-11-06 10:32 UTC, vinceAmstoutz commented on app/Resources/views/event/switch.html.twig
> +                        <svg width="32" height="32"><use xlink:href="#octocat"></use></svg>
C'est supprimé, j'ai oublié de l'enlever quand je me suis basé sur le design des autres. Merci ! A voir si ca convient à @agallou s'il y en a pas

2022-11-06 11:01 UTC, vinceAmstoutz commented on sources/AppBundle/Event/Model/Repository/EventRepository.php
> +    }
Bien vu, en effet il n'y a plus besoin vis à vis de ce que j'ai fais dans le contrôleur désormais. C'est revert vers le commit d'origine !

2022-11-06 13:18 UTC, stakovicz commented on app/Resources/views/event/menu.html.twig
> +                <a class="navbar-brand hidden-xs" href="/event">{{ 'Évènements'|trans }}</a>
Ha OK ... je viens de comprendre !
Effectivement, je croyais que c'était le menu global du site.

Ça marche pour moi, désolé pour la remarque.

2022-11-06 13:19 UTC, stakovicz approved these changes

2022-11-06 13:26 UTC, vinceAmstoutz commented on app/Resources/views/event/menu.html.twig
> +                <a class="navbar-brand hidden-xs" href="/event">{{ 'Évènements'|trans }}</a>
Pas de soucis, tu as bien fait, merci pour ton retour !

2022-11-08 12:17 UTC, merged

2022-11-08 12:32 UTC, agallou commented
Merci @vinceAmstoutz 
C'est mis en prod et ça fonctionne https://afup.org/event/
(j'attends que la redirection sur Gandi depuis https://cfp.afup.org soit effective d'ici quelques heures et en parle sur la room des news)