correction du build suite à la sortie de bookworm
afup/web pull request #1304
Opened 2023-06-18 20:02 UTC by agallou

Avec la sortie de bookwork, strech qui était en lts est passée en archivée cf https://www.debian.org/releases/stretch/

et https://www.debian.org/distrib/archive

On avait des erreurs comme celle-ci lors du build :

```
Reading package lists...
W: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
W: The repository 'http://archive.debian.org/debian stretch-updates Release' does not have a Release file.
E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages  404  Not Found [IP: 151.101.194.132 80]
E: Failed to fetch http://archive.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  404  Not Found [IP: 130.89.148.13 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Afin de les éviter on passe sur le dépot d'archives.

2023-06-21 08:49 UTC, stakovicz requested changes

2023-06-21 08:49 UTC, stakovicz commented on docker/dockerfiles/apachephp/Dockerfile
> +RUN echo 'deb http://archive.debian.org/debian stretch main' > /etc/apt/sources.list
Je pense qu'il faut l'ajouter dans le Dockerfile de apachephp7 et planete, non?

2023-06-28 11:49 UTC, agallou commented on docker/dockerfiles/apachephp/Dockerfile
> +RUN echo 'deb http://archive.debian.org/debian stretch main' > /etc/apt/sources.list
oui, je viens de le modifier

2023-06-28 11:50 UTC, stakovicz approved these changes

2023-06-28 12:40 UTC, merged