Feat 1313 sponsorship request form add job title
afup/web pull request #1436
Opened 2024-02-03 23:04 UTC by vinceAmstoutz

Solves #1313 

- Ajout du champ "Poste"
- Ajout des tests fonctionnels manquants

2024-02-04 13:44 UTC, stakovicz requested changes
Bravo pour cette PR !

Il manque simplement le fichier de migration de la base de données.
Tu peux t'inspirer de celui-ci par exemple :
https://github.com/afup/web/blob/master/db/migrations/20231206213600_tva_intra_compta.php

2024-02-04 14:08 UTC, vinceAmstoutz commented
> Bravo pour cette PR !
> 
> Il manque simplement le fichier de migration de la base de données.
> Tu peux t'inspirer de celui-ci par exemple :
> https://github.com/afup/web/blob/master/db/migrations/20231206213600_tva_intra_compta.php

Je pensais que c'était juste un envoi de mail vu comme c'était expliqué dans le ticket, je me suis trompée ? Si oui on stocke ça dans quelle table ?

2024-02-04 14:30 UTC, stakovicz approved these changes
Et bien effectivement, j'ai mal compris la demande.
C'est tout bon pour moi alors !

2024-02-04 14:46 UTC, vinceAmstoutz commented
> Et bien effectivement, j'ai mal compris la demande.
> C'est tout bon pour moi alors !

No soucis, merci!

2024-02-22 18:56 UTC, agallou approved these changes

2024-02-22 19:05 UTC, merged